#include <iostream>

using namespace std;

int main()
{
	FUCK YOU JAMIE FLECK AND YOUR GOALS, YOU CAN GO FUCK YOURSELF... GIT


		GIT MUST BE GAY BECAUSE IT LOVES TO FUCK ME IN THE ASSS FOR HOURS OVER SOMETHING SIMPLE....

	}
}